# Generated by Django 2.2 on 2019-10-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badhon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
    ]
