# Generated by Django 2.2 on 2019-10-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badhon', '0002_auto_20191011_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(default='A+', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='slug',
            field=models.SlugField(default='tipu', unique=True),
            preserve_default=False,
        ),
    ]
