# Generated by Django 2.2 on 2019-10-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badhon', '0004_donor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
